const BASE = 'https://al-jawhara.com/wp-content/uploads';

export const clients = [
  // ── تجزئة ──────────────────────────────────────────────
  { name: 'City Center',       nameAr: 'سيتي سنتر',              sectorKey: 'retail',       logo: '/logos/CityCenter.png' },
  { name: 'Carrefour',         nameAr: 'كارفور',                  sectorKey: 'retail',       logo: '/logos/carrefour.png' },
  { name: 'Sultan Center',     nameAr: 'سلطان سنتر',              sectorKey: 'retail',       logo: '/logos/sultan.png' },
  { name: 'Lulu Hypermarket',  nameAr: 'لولو هايبر ماركت',         sectorKey: 'retail',       logo: '/logos/lulu.png' },
  { name: 'Oncost',            nameAr: 'أونكوست',                 sectorKey: 'retail',       logo: '/logos/Oncost.png' },
  { name: 'SaveCo',            nameAr: 'سيفكو',                 sectorKey: 'retail',       logo: '/logos/SaveCo.png' },

  // ── جمعيات تعاونية ─────────────────────────────────────
  { name: 'Romaitha',          nameAr: 'جمعية الرميثاء',          sectorKey: 'coops',        logo: '/logos/Romaitha.png' },
  { name: "Ta3awnieh",         nameAr: 'التعاونية',               sectorKey: 'coops',        logo: '/logos/Ta3awnieh.png' },
  { name: 'Wafra',             nameAr: 'جمعية الوفرة',            sectorKey: 'coops',        logo: `${BASE}/2021/03/Wafra.png` },
  { name: 'Dahia',             nameAr: 'جمعية الضاحية',           sectorKey: 'coops',        logo: `${BASE}/2021/03/Dahia.png` },
  { name: 'Naim',              nameAr: 'جمعية النعيم',            sectorKey: 'coops',        logo: `${BASE}/2021/03/Naim.png` },
  { name: 'Solibikhat',        nameAr: 'جمعية الصليبيخات',        sectorKey: 'coops',        logo: `${BASE}/2021/03/Solibikhat.png` },
  { name: 'Salwa',             nameAr: 'جمعية سلوى',              sectorKey: 'coops',        logo: '/logos/Salwa.png' },
  { name: 'Jabrieh',           nameAr: 'جمعية الجابرية',          sectorKey: 'coops',        logo: `${BASE}/2021/03/Jabrieh.png` },
  { name: 'Saad',              nameAr: 'جمعية سعد العبدالله',     sectorKey: 'coops',        logo: '/logos/Saad.png' },
  { name: 'Sora',              nameAr: 'جمعية الصوابر',           sectorKey: 'coops',        logo: `${BASE}/2021/03/Sora.png` },
  { name: 'Salam',             nameAr: 'جمعية السلام',            sectorKey: 'coops',        logo: '/logos/Salam.png' },
  { name: 'Adan',              nameAr: 'جمعية العدان',            sectorKey: 'coops',        logo: '/logos/Adan.png' },
  { name: 'Jothen',            nameAr: 'جمعية الجثوم',            sectorKey: 'coops',        logo: `${BASE}/2021/03/Jothen.png` },
  { name: 'Salmieh',           nameAr: 'جمعية السالمية',          sectorKey: 'coops',        logo: '/logos/Salmieh.png' },
  { name: 'Bayan',             nameAr: 'جمعية البيان',            sectorKey: 'coops',        logo: '/logos/Bayan.png' },
  { name: 'Kaifan',            nameAr: 'جمعية كيفان',             sectorKey: 'coops',        logo: '/logos/Kaifan.png' },
  { name: 'Khaldieh',          nameAr: 'جمعية الخالدية',          sectorKey: 'coops',        logo: `${BASE}/2021/03/Khaldieh.png` },
  { name: 'Abdali',            nameAr: 'جمعية العبدلي',           sectorKey: 'coops',        logo: `${BASE}/2021/03/Abdali.png` },
  { name: 'Souq',              nameAr: 'سوق',                     sectorKey: 'coops',        logo: `${BASE}/2021/03/Souq.png` },
  { name: 'Chamieh',           nameAr: 'جمعية الشامية',           sectorKey: 'coops',        logo: '/logos/Chamieh.png' },
  { name: 'Ahmadi',            nameAr: 'جمعية الأحمدي',           sectorKey: 'coops',        logo: '/logos/Ahmadi.png' },
  { name: 'Shohadaa',          nameAr: 'جمعية الشهداء',           sectorKey: 'coops',        logo: '/logos/Shohadaa.png' },
  { name: 'Shaab',             nameAr: 'جمعية الشعب',             sectorKey: 'coops',        logo: '/logos/Shaab.png' },
  { name: 'Sadeek',            nameAr: 'جمعية الصديق',            sectorKey: 'coops',        logo: '/logos/Sadeek.png' },
  { name: 'Saber Ali',         nameAr: 'جمعية صبر علي',           sectorKey: 'coops',        logo: '/logos/SaberAli.png' },
  { name: 'Sabah Ahmad',       nameAr: 'جمعية صباح الأحمد',       sectorKey: 'coops',        logo: '/logos/SabahAhmad.png' },
  { name: 'Reqa',              nameAr: 'جمعية الرقعي',            sectorKey: 'coops',        logo: '/logos/Reqa.png' },
  { name: 'Qayrawan',          nameAr: 'جمعية القيروان',          sectorKey: 'coops',        logo: '/logos/Qayrawan.png' },
  { name: 'Halifah',           nameAr: 'جمعية الخليفات',          sectorKey: 'coops',        logo: '/logos/Halifah.png' },
  { name: 'Fayhaa',            nameAr: 'جمعية الفيحاء',           sectorKey: 'coops',        logo: '/logos/Fayhaa.png' },
  { name: 'Fahaihel',          nameAr: 'جمعية الفحيحيل',          sectorKey: 'coops',        logo: '/logos/Fahaihel.png' },
  { name: 'Salibieh',          nameAr: 'جمعية الصليبية',          sectorKey: 'coops',        logo: '/logos/Salibieh.png' },
  { name: 'Farwanieh',         nameAr: 'جمعية الفروانية',          sectorKey: 'coops',        logo: '/logos/Farwanieh.png' },
  { name: 'Gharnata',          nameAr: 'جمعية غرناطة',           sectorKey: 'coops',        logo: '/logos/Gharnata.png' },
  { name: 'Khaytan',           nameAr: 'جمعية خيطان',            sectorKey: 'coops',        logo: '/logos/Khaytan.png' },
  { name: 'Manqaf',            nameAr: 'جمعية المنقف',            sectorKey: 'coops',        logo: '/logos/Manqaf.png' },
  { name: 'Yarmouk',           nameAr: 'جمعية اليرموك',            sectorKey: 'coops',        logo: '/logos/Yarmouk.png' },

  // ── كافيهات ─────────────────────────────────────────────
  { name: 'Starbucks',         nameAr: 'ستاربكس',                 sectorKey: 'cafes',        logo: '/logos/starbucks.png' },
  { name: 'Bell Cafe',         nameAr: 'بيل كافيه',               sectorKey: 'cafes',        logo: '/logos/BellCafe.png' },
  { name: 'Zoom',              nameAr: 'زووم',                    sectorKey: 'cafes',        logo: '/logos/Zoom.png' },
  { name: 'Second Cup',        nameAr: 'سكند كاب',                sectorKey: 'cafes',        logo: '/logos/SecondCup.png' },
  { name: 'Coffee',            nameAr: 'كوفي',                    sectorKey: 'cafes',        logo: '/logos/Coffee.png' },
  { name: '21 Degrees',        nameAr: '21 درجة',                 sectorKey: 'cafes',        logo: '/logos/21degrees.png' },

  // ── مطاعم ───────────────────────────────────────────────
  { name: "Chili's",           nameAr: 'تشيليز',                  sectorKey: 'restaurants',  logo: '/logos/Chilis.png' },
  { name: 'Kababji',           nameAr: 'كبابجي',                  sectorKey: 'restaurants',  logo: '/logos/Kababji.png' },
  { name: 'Fouchon',           nameAr: 'فوشون',                   sectorKey: 'restaurants',  logo: '/logos/Fouchon.png' },
  { name: 'Maraya',            nameAr: 'مرايا',                   sectorKey: 'restaurants',  logo: '/logos/Maraya.png' },
  { name: 'Marsa',             nameAr: 'مرسى',                    sectorKey: 'restaurants',  logo: '/logos/Marsa.png' },
  { name: 'Nurai',             nameAr: 'نوراي',                   sectorKey: 'restaurants',  logo: '/logos/Nurai.png' },
  { name: 'Offside',           nameAr: 'أوفسايد',                 sectorKey: 'restaurants',  logo: '/logos/Offside.png' },
  { name: 'Casa',              nameAr: 'كاسا',                    sectorKey: 'restaurants',  logo: '/logos/casa.png' },
  { name: 'E-Club',            nameAr: 'إي كلوب',                 sectorKey: 'restaurants',  logo: '/logos/eclub.png' },
  { name: 'Pavillion',         nameAr: 'بافيليون',                sectorKey: 'restaurants',  logo: '/logos/Pavillion.png' },
  { name: 'Khoukh',            nameAr: 'الخوخ',                   sectorKey: 'restaurants',  logo: '/logos/Khoukh.png' },
  { name: 'Izmir',             nameAr: 'إزمير',                   sectorKey: 'restaurants',  logo: '/logos/Izmir.png' },
  { name: 'Harayer',           nameAr: 'حراير',                   sectorKey: 'restaurants',  logo: '/logos/Harayer.png' },
  { name: 'Mais',              nameAr: 'ميس',                     sectorKey: 'restaurants',  logo: '/logos/Mais.png' },
  { name: 'Kasap',             nameAr: 'كساب',                    sectorKey: 'restaurants',  logo: '/logos/Kasap.png' },
  { name: 'Lite',              nameAr: 'لايت',                    sectorKey: 'restaurants',  logo: '/logos/Lite.png' },
  { name: 'Dosary',            nameAr: 'الدوسري',                 sectorKey: 'restaurants',  logo: '/logos/Dosary.png' },
  { name: 'Crepe',             nameAr: 'كريب',                    sectorKey: 'restaurants',  logo: '/logos/Crepe.png' },
  { name: 'Cacoa',             nameAr: 'كاكاو',                   sectorKey: 'restaurants',  logo: '/logos/Cacoa.png' },
  { name: 'Bun',               nameAr: 'بن',                      sectorKey: 'restaurants',  logo: '/logos/Bun.png' },
  { name: 'Alpanetto',         nameAr: 'ألبانيتو',                sectorKey: 'restaurants',  logo: '/logos/Alpanetto.png' },
  { name: 'Which Wich',        nameAr: 'ويتش ويتش',               sectorKey: 'restaurants',  logo: '/logos/Which.png' },
  { name: 'Spice',             nameAr: 'سبايس',                   sectorKey: 'restaurants',  logo: '/logos/Spice.png' },
  { name: 'Shrimpy',           nameAr: 'شريمبي',                  sectorKey: 'restaurants',  logo: '/logos/Shrimpy.png' },
  { name: 'Seal',              nameAr: 'سيل',                     sectorKey: 'restaurants',  logo: '/logos/Seal.png' },
  { name: 'Safir',             nameAr: 'السفير',                  sectorKey: 'restaurants',  logo: '/logos/Safir.png' },
  { name: 'Rodan',             nameAr: 'رودان',                   sectorKey: 'restaurants',  logo: '/logos/Rodan.png' },
  { name: 'Plams',             nameAr: 'بلامز',                   sectorKey: 'restaurants',  logo: '/logos/Plams.png' },
  { name: 'Ocean Basket',      nameAr: 'أوشن باسكت',              sectorKey: 'restaurants',  logo: '/logos/OceanBasket.png' },
  { name: 'Maazzib',           nameAr: 'معازيب',                  sectorKey: 'restaurants',  logo: '/logos/Maazzib.png' },
  { name: 'Le Royal',          nameAr: 'لو رويال',                sectorKey: 'restaurants',  logo: '/logos/LeRoyal.png' },
  { name: 'Lazurd',            nameAr: 'لازورد',                  sectorKey: 'restaurants',  logo: '/logos/Lazurd.png' },
  { name: 'Land of Tahi',      nameAr: 'لاند أوف تاهي',          sectorKey: 'restaurants',  logo: '/logos/LandofTahi.png' },
  { name: 'Kosebasi',          nameAr: 'كوزيباشي',                sectorKey: 'restaurants',  logo: '/logos/Kosebasi.png' },
  { name: 'Jani',              nameAr: 'جاني',                    sectorKey: 'restaurants',  logo: '/logos/Jani.png' },
  { name: 'Hush',              nameAr: 'هاش',                     sectorKey: 'restaurants',  logo: '/logos/Hush.png' },
  { name: 'Gia',               nameAr: 'جيا',                     sectorKey: 'restaurants',  logo: '/logos/Gia.png' },
  { name: 'Frosting',          nameAr: 'فروستينج',                sectorKey: 'restaurants',  logo: '/logos/Frosting.png' },
  { name: 'Franji',            nameAr: 'فرنجي',                   sectorKey: 'restaurants',  logo: '/logos/Franji.png' },
  { name: 'Diet Car',          nameAr: 'دايت كار',                sectorKey: 'restaurants',  logo: '/logos/DietCar.png' },
  { name: 'Danish',            nameAr: 'دانيش',                   sectorKey: 'restaurants',  logo: '/logos/DANISH.png' },
  { name: 'Crazy Chicken',     nameAr: 'كريزي تشيكن',             sectorKey: 'restaurants',  logo: '/logos/CrazyChicken.png' },
  { name: 'Cardamon',          nameAr: 'كاردامون',                sectorKey: 'restaurants',  logo: '/logos/Cardamon.png' },
  { name: 'Bee Salt',          nameAr: 'بي سالت',                 sectorKey: 'restaurants',  logo: '/logos/BeeSalt.png' },
  { name: 'Bazza',             nameAr: 'بازا',                    sectorKey: 'restaurants',  logo: '/logos/Bazza.png' },
  { name: 'Ayyame',            nameAr: 'أيامي',                   sectorKey: 'restaurants',  logo: '/logos/Ayyame.png' },
  { name: "Applebee's",        nameAr: 'آبلبيز',                  sectorKey: 'restaurants',  logo: '/logos/Applebees.png' },
  { name: 'Anoosh',            nameAr: 'أنوش',                    sectorKey: 'restaurants',  logo: '/logos/Anoosh.png' },
  { name: 'Adams',             nameAr: 'آدامز',                   sectorKey: 'restaurants',  logo: '/logos/Adams.png' },
  { name: 'Burj Al Hamam',     nameAr: 'برج الحمام',              sectorKey: 'restaurants',  logo: '/logos/Hamam.png' },

  // ── توصيل طعام ─────────────────────────────────────────
  { name: 'Talabat',           nameAr: 'طلبات',                   sectorKey: 'delivery',     logo: '/logos/talabat.png' },
  { name: 'Taw9eel',           nameAr: 'توصيل',                   sectorKey: 'delivery',     logo: '/logos/taw9eel.png' },
  { name: 'Trolley',           nameAr: 'تروليه',                  sectorKey: 'delivery',     logo: '/logos/trolley.png' },

  // ── فنادق ونوادي ────────────────────────────────────────
  { name: 'Regency',           nameAr: 'ريجنسي',                  sectorKey: 'hotels',       logo: '/logos/Regency.png' },
  { name: 'Raddison',          nameAr: 'راديسون',                 sectorKey: 'hotels',       logo: '/logos/Raddison.png' },
  { name: 'Novitta',           nameAr: 'نوفيتا',                  sectorKey: 'hotels',       logo: '/logos/Novitta.png' },
  { name: 'New Park',          nameAr: 'نيو بارك',                sectorKey: 'hotels',       logo: '/logos/NewPark.png' },
  { name: 'Mobarak',           nameAr: 'المبارك',                 sectorKey: 'hotels',       logo: '/logos/Mobarak.png' },
  { name: 'Royal',             nameAr: 'رويال',                   sectorKey: 'hotels',       logo: '/logos/Royal.png' },
  { name: 'Jazeera',           nameAr: 'الجزيرة',                 sectorKey: 'hotels',       logo: '/logos/Jazeera.png' },
  { name: 'Fatira',            nameAr: 'فطيرة',                   sectorKey: 'hotels',       logo: '/logos/Fatira.png' },
  { name: 'Wezara',            nameAr: 'الوزارة',                 sectorKey: 'hotels',       logo: '/logos/Wezara.png' },
];
