const BASE = 'https://al-jawhara.com/wp-content/uploads';

export const clients = [
  // ── تجزئة ──────────────────────────────────────────────
  { name: 'City Center',       nameAr: 'سيتي سنتر',              sectorKey: 'retail',       logo: '/logos/CityCenter.png' },
  { name: 'Carrefour',         nameAr: 'كارفور',                  sectorKey: 'retail',       logo: '/logos/carrefour.png' },
  { name: 'Sultan Center',     nameAr: 'سلطان سنتر',              sectorKey: 'retail',       logo: '/logos/sultan.png' },
  { name: 'Oncost',            nameAr: 'أونكوست',                 sectorKey: 'retail',       logo: '/logos/Oncost.png' },

  // ── جمعيات تعاونية ─────────────────────────────────────
  { name: 'Romaitha',          nameAr: 'جمعية الرميثة',           sectorKey: 'coops',        logo: '/logos/Romaitha.png' },
  { name: 'Wafra',             nameAr: 'جمعية الوفرة',            sectorKey: 'coops',        logo: `${BASE}/2021/03/Wafra.png` },
  { name: 'Dahia',             nameAr: 'جمعية الضاحية',           sectorKey: 'coops',        logo: `${BASE}/2021/03/Dahia.png` },
  { name: 'Naim',              nameAr: 'جمعية النعيم',            sectorKey: 'coops',        logo: `${BASE}/2021/03/Naim.png` },
  { name: 'Solibikhat',        nameAr: 'جمعية الصليبيخات',        sectorKey: 'coops',        logo: `${BASE}/2021/03/Solibikhat.png` },
  { name: 'Salwa',             nameAr: 'جمعية سلوى',              sectorKey: 'coops',        logo: '/logos/Salwa.png' },
  { name: 'Jabrieh',           nameAr: 'جمعية الجابرية',          sectorKey: 'coops',        logo: `${BASE}/2021/03/Jabrieh.png` },
  { name: 'Saad',              nameAr: 'جمعية سعد العبدالله',     sectorKey: 'coops',        logo: '/logos/Saad.png' },
  { name: 'Sora',              nameAr: 'جمعية الصوابر',           sectorKey: 'coops',        logo: `${BASE}/2021/03/Sora.png` },
  { name: 'Salam',             nameAr: 'جمعية السلام',            sectorKey: 'coops',        logo: '/logos/Salam.png' },
  { name: 'Adan',              nameAr: 'جمعية العدان',            sectorKey: 'coops',        logo: '/logos/Adan.png' },
  { name: 'Jothen',            nameAr: 'جمعية الجثوم',            sectorKey: 'coops',        logo: `${BASE}/2021/03/Jothen.png` },
  { name: 'Salmieh',           nameAr: 'جمعية السالمية',          sectorKey: 'coops',        logo: '/logos/Salmieh.png' },
  { name: 'Bayan',             nameAr: 'جمعية بيان',              sectorKey: 'coops',        logo: '/logos/Bayan.png' },
  { name: 'Kaifan',            nameAr: 'جمعية كيفان',             sectorKey: 'coops',        logo: '/logos/Kaifan.png' },
  { name: 'Khaldieh',          nameAr: 'جمعية الخالدية',          sectorKey: 'coops',        logo: `${BASE}/2021/03/Khaldieh.png` },
  { name: 'Abdali',            nameAr: 'جمعية العبدلي',           sectorKey: 'coops',        logo: `${BASE}/2021/03/Abdali.png` },
  { name: 'Souq',              nameAr: 'سوق',                     sectorKey: 'coops',        logo: `${BASE}/2021/03/Souq.png` },
  { name: 'Chamieh',           nameAr: 'جمعية الشامية',           sectorKey: 'coops',        logo: '/logos/Chamieh.png' },
  { name: 'Ahmadi',            nameAr: 'جمعية الأحمدي',           sectorKey: 'coops',        logo: '/logos/Ahmadi.png' },
  { name: 'Shohadaa',          nameAr: 'جمعية الشهداء',           sectorKey: 'coops',        logo: '/logos/Shohadaa.png' },
  { name: 'Shaab',             nameAr: 'جمعية الشعب',             sectorKey: 'coops',        logo: '/logos/Shaab.png' },
  { name: 'Sadeek',            nameAr: 'جمعية الصديق',            sectorKey: 'coops',        logo: '/logos/Sadeek.png' },
  { name: 'Jaber Al-Ali',      nameAr: 'جمعية جابر العلي',        sectorKey: 'coops',        logo: '/logos/SaberAli.png' },
  { name: 'Sabah Ahmad',       nameAr: 'جمعية صباح الأحمد',       sectorKey: 'coops',        logo: '/logos/SabahAhmad.png' },
  { name: 'Reqa',              nameAr: 'جمعية الرقعي',            sectorKey: 'coops',        logo: '/logos/Reqa.png' },
  { name: 'Qayrawan',          nameAr: 'جمعية القيروان',          sectorKey: 'coops',        logo: '/logos/Qayrawan.png' },
  { name: 'Fayhaa',            nameAr: 'جمعية الفيحاء',           sectorKey: 'coops',        logo: '/logos/Fayhaa.png' },
  { name: 'Fahaihel',          nameAr: 'جمعية الفحيحيل',          sectorKey: 'coops',        logo: '/logos/Fahaihel.png' },
  { name: 'Salibieh',          nameAr: 'جمعية الصليبية',          sectorKey: 'coops',        logo: '/logos/Salibieh.png' },
  { name: 'Farwanieh',         nameAr: 'جمعية الفروانية',          sectorKey: 'coops',        logo: '/logos/Farwanieh.png' },
  { name: 'Gharnata',          nameAr: 'جمعية غرناطة',           sectorKey: 'coops',        logo: '/logos/Gharnata.png' },
  { name: 'Khaytan',           nameAr: 'جمعية خيطان',            sectorKey: 'coops',        logo: '/logos/Khaytan.png' },
  { name: 'Manqaf',            nameAr: 'جمعية المنقف',            sectorKey: 'coops',        logo: '/logos/Manqaf.png' },
  { name: 'Yarmouk',           nameAr: 'جمعية اليرموك',            sectorKey: 'coops',        logo: '/logos/Yarmouk.png' },
  { name: 'Abu Fatira',        nameAr: 'جمعية أبو فطيرة',         sectorKey: 'coops',        logo: '/logos/Fatira.png' },

  // ── كافيهات ─────────────────────────────────────────────
  { name: 'Starbucks',         nameAr: 'ستاربكس',                 sectorKey: 'cafes',        logo: '/logos/starbucks.png' },
  { name: 'Coffee',            nameAr: 'كوفي',                    sectorKey: 'cafes',        logo: '/logos/Coffee.png' },

  // ── مطاعم ───────────────────────────────────────────────
  { name: "Chili's",           nameAr: 'تشيليز',                  sectorKey: 'restaurants',  logo: '/logos/chilis.png' },
  { name: 'Kababji',           nameAr: 'كبابجي',                  sectorKey: 'restaurants',  logo: '/logos/Kababji.png' },
  { name: 'Maraya Al Khaleej', nameAr: 'مرايا الخليج',            sectorKey: 'restaurants',  logo: '/logos/Maraya.png' },
  { name: 'E-Club',            nameAr: 'إي كلوب',                 sectorKey: 'restaurants',  logo: '/logos/eclub.png' },
  { name: 'Kasap',             nameAr: 'كساب',                    sectorKey: 'restaurants',  logo: '/logos/Kasap.png' },
  { name: 'Lite',              nameAr: 'لايت',                    sectorKey: 'restaurants',  logo: '/logos/Lite.png' },
  { name: 'Shrimpy',           nameAr: 'شريمبي',                  sectorKey: 'restaurants',  logo: '/logos/Shrimpy.png' },
  { name: 'Safir',             nameAr: 'السفير',                  sectorKey: 'restaurants',  logo: '/logos/Safir.png' },
  { name: 'Ocean Basket',      nameAr: 'أوشن باسكت',              sectorKey: 'restaurants',  logo: '/logos/OceanBasket.png' },
  { name: 'Le Royal',          nameAr: 'لو رويال',                sectorKey: 'restaurants',  logo: '/logos/LeRoyal.png' },
  { name: 'Gia',               nameAr: 'جيا',                     sectorKey: 'restaurants',  logo: '/logos/Gia.png' },
  { name: 'Frosting',          nameAr: 'فروستينج',                sectorKey: 'restaurants',  logo: '/logos/Frosting.png' },
  { name: 'Diet Car',          nameAr: 'دايت كار',                sectorKey: 'restaurants',  logo: '/logos/DietCar.png' },
  { name: 'Crazy Chicken',     nameAr: 'كريزي تشيكن',             sectorKey: 'restaurants',  logo: '/logos/CrazyChicken.png' },
  { name: 'Bazza',             nameAr: 'بازا',                    sectorKey: 'restaurants',  logo: '/logos/Bazza.png' },
  { name: 'Ayyame',            nameAr: 'أيامي',                   sectorKey: 'restaurants',  logo: '/logos/Ayyame.png' },
  { name: "Applebee's",        nameAr: 'آبلبيز',                  sectorKey: 'restaurants',  logo: '/logos/Applebees.png' },
  { name: 'Adams',             nameAr: 'آدامز',                   sectorKey: 'restaurants',  logo: '/logos/Adams.png' },

  // ── توصيل طعام ─────────────────────────────────────────
  { name: 'Talabat',           nameAr: 'طلبات',                   sectorKey: 'delivery',     logo: '/logos/talabat.png' },
  { name: 'Taw9eel',           nameAr: 'توصيل',                   sectorKey: 'delivery',     logo: '/logos/taw9eel.png' },
  { name: 'Trolley',           nameAr: 'تروليه',                  sectorKey: 'delivery',     logo: '/logos/trolley.png' },

  // ── فنادق ونوادي ────────────────────────────────────────
  { name: 'Regency',           nameAr: 'ريجنسي',                  sectorKey: 'hotels',       logo: '/logos/Regency.png' },
  { name: 'Raddison',          nameAr: 'راديسون',                 sectorKey: 'hotels',       logo: '/logos/Raddison.png' },
  { name: 'Royal',             nameAr: 'رويال',                   sectorKey: 'hotels',       logo: '/logos/Royal.png' },
  { name: 'Jazeera',           nameAr: 'الجزيرة',                 sectorKey: 'hotels',       logo: '/logos/Jazeera.png' },

  // ── مستشفيات ────────────────────────────────────────────
  { name: 'Dar Al Shifa Hospital',    nameAr: 'مستشفى دار الشفا',   sectorKey: 'hospitals',    logo: '/logos/DarAlShifa.png' },
  { name: 'Al Salam Hospital',        nameAr: 'مستشفى السلام',      sectorKey: 'hospitals',    logo: '/logos/SalamHospital.jpg' },
  { name: 'Al Mowasat Hospital',      nameAr: 'مستشفى المواساة',    sectorKey: 'hospitals',    logo: '/logos/Mowasat.svg' },
  { name: 'Taiba Hospital',           nameAr: 'مستشفى طيبة',        sectorKey: 'hospitals',    logo: '/logos/Taiba.png' },
  { name: 'Sidra Hospital',           nameAr: 'مستشفى سدرة',        sectorKey: 'hospitals',    logo: '/logos/Sidra.png' },
  { name: 'International Hospital',   nameAr: 'المستشفى الدولي',    sectorKey: 'hospitals',    logo: '/logos/InternationalHospital.png' },
  { name: 'Kuwait Hospital',          nameAr: 'مستشفى الكويت',      sectorKey: 'hospitals',    logo: '/logos/KuwaitHospital.png' },
  { name: 'Al Seef Hospital',         nameAr: 'مستشفى السيف',       sectorKey: 'hospitals',    logo: '/logos/AlSeef.png' },
  { name: 'Alia International Hospital', nameAr: 'مستشفى عالية الدولي', sectorKey: 'hospitals', logo: '/logos/Aalia.svg' },
  { name: 'Al Orf Hospital',          nameAr: 'مستشفى العرف',       sectorKey: 'hospitals',    logo: '/logos/AlOrf.gif' },
  { name: 'Hadi Clinic',              nameAr: 'مستشفى هادي',        sectorKey: 'hospitals',    logo: '/logos/Hadi.svg' },
];
